ID = "id"
STAGE = "stage"
STAGE_VARIABLES = "stageVariables"
QUERY_STRING_PARAMETERS = "queryStringParameters"
BLOCKED_STATUS = "Vermittlung gescheitert"
TEXT_PLAIN = "text/plain"
APPLICATION_JSON = "application/json"
ALLOW_ORIGIN = "*"
ALLOW_HEADERS = "Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, X-Amz-User-Agent"
ALLOW_METHODS = "OPTIONS,GET,PUT,POST,DELETE,PATCH,HEAD"
BODY = 'body'
HEADERS = 'headers'
TEXT_HTML = "text/html"
STATUS_CODE = 'statusCode'
HTTP_METHOD = "httpMethod"
CONTENT_TYPE = "Content-Type"
PAYLOAD = 'Payload'
REQUEST_CONTEXT = 'requestContext'
AUTHORIZER = 'authorizer'
ALGORITHM = 'HS256'
